image: mcr.microsoft.com/dotnet/core/sdk:5.0

stages:
    - build
    - test

before_script:
    - "cd server"
    - "dotnet restore SelfServiceLibrary.sln"

build:
    stage: build
    script:
        - "dotnet build SelfServiceLibrary.sln"

test:
    stage: test
    script:
        - "dotnet test SelfServiceLibrary.sln"
