image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
    - test

before_script:
    - "cd server"
    - "dotnet restore SelfServiceLibrary.sln"

test:
    stage: test
    script:
        - "dotnet test SelfServiceLibrary.sln"
