version: '3.4'

services:
  books.db:
    image: mongo:4.4
    environment:
      MONGO_INITDB_DATABASE: BooksDb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    expose:
      - "27017"
    volumes:
      - mongodb_data_container:/data/db

  selfservicelibrary.api:
    image: skalahonza/self-service-library-api:latest
    environment:
      - MongoDb__ConnectionString=mongodb://root:rootpassword@books.db:27017
      - Identity__ConnectionString=mongodb://root:rootpassword@books.db:27017/identity
      - MongoDb__DatabaseName=BooksDb
    build:
      context: .
      dockerfile: SelfServiceLibrary.API/Dockerfile

  selfservicelibrary.web:
    image: skalahonza/self-service-library-web:latest
    environment:
      - MongoDb__ConnectionString=mongodb://root:rootpassword@books.db:27017
      - Identity__ConnectionString=mongodb://root:rootpassword@books.db:27017/identity
      - MongoDb__DatabaseName=BooksDb
    build:
      context: .
      dockerfile: SelfServiceLibrary.Web/Dockerfile

volumes:
  mongodb_data_container: